services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio:/data
    container_name: daw-bh-s3minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    container_name: daw-bh-redis
    restart: on-failure
    volumes:
      - ./redis:/data

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    container_name: daw-bh-mysql
    environment:
      - MYSQL_DATABASE=daw-bh
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3307'
    volumes:
      - ./mysql:/var/lib/mysql
